### ISSUE TITLE
Non-BMP characters broken in HN titles

### ISSUE THREAD

**Issue by yuhong** [algolia/hn-search#104]
Searching for https://news.ycombinator.com/item?id=15678471 cause the non-BMP character in the title to be U+FFFD

**Comment by Haroenv** [comment]
thanks for noticing that @yuhong, we are aware of this issue, and it's broader than just the HN search. There currently isn't really a fix possible, since our engine internally uses UCS-2 in most places. We are already working on making it completely UTF-16; but as you're probably aware, that's not without some technical hurdles. I'll keep this issue open for when we fix the underlying issue. 

Thanks!
