### ISSUE TITLE
Different number of results for Popularity vs Date

### ISSUE THREAD

**Issue by pbowyer** [algolia/hn-search#122]
https://hn.algolia.com/?query=infinion&sort=byPopularity&prefix&page=0&dateRange=all&type=comment
![image](https://user-images.githubusercontent.com/89852/42041348-a489e25a-7ae9-11e8-9ca6-da088aa75a04.png)

https://hn.algolia.com/?query=infinion&sort=byDate&prefix&page=0&dateRange=all&type=comment
![image](https://user-images.githubusercontent.com/89852/42041387-b8ce4634-7ae9-11e8-8743-4deeb5a60c49.png)

IMO sorting by Popularity vs Date should not reduce the search results by 376 records! I expect all 378 ordered by newest => oldest.

**Comment by Haroenv** [comment]
<img width="1195" alt="screen shot 2018-07-02 at 09 30 08" src="https://user-images.githubusercontent.com/6270048/42150558-8e7a505a-7dda-11e8-8ff3-532be6235fda.png">
<img width="1209" alt="screen shot 2018-07-02 at 09 30 02" src="https://user-images.githubusercontent.com/6270048/42150560-8e947098-7dda-11e8-94a3-c13f0b3d45f4.png">

Something weird is happening here @redox; when I do the same query multiple times on the dashboard it fluctuates between 500 and 10 results, but on the site I get the same 400/2 results like in the original screenshot. Any idea what could cause this?

**Comment by redox** [comment]
The fluctuation is expected; it's timeouting because the index is so big. @Haroenv 

@pbowyer Regarding the diff in the number of hits, it's because when we sort by date we explicitely disable typo-tolerance in the UI. It's something we recommend to avoid having - in this case - very old/fresh content matching approximatively before the others. While sorting by popularity, we don't really care to have approximative match in the results list because anyway the more relevant will be first.

Does that make sense?
