### ISSUE TITLE
Search text doesn't change color in Safari when in Apple system dark mode

### ISSUE THREAD

**Issue by quinnblay** [algolia/hn-search#177]
When in the Apple system dark mode and using the Safari browser, it'd be great if the text in the search bar changed color / contrast for easier viewing at night.

<img width="1667" alt="image" src="https://user-images.githubusercontent.com/7497719/76138217-92592580-5ffa-11ea-9cc6-a156a288c1ba.png">

**Comment by Shipow** [comment]
Good catch, it happens when you change the theme from experimental to regular while having the dark theme option enabled.
To fix it on your UI you can access back the options in the experimental theme: 
![image](https://user-images.githubusercontent.com/976175/76139725-5ef6b500-6053-11ea-9632-625a813a688e.png) or cleaning your cookies should work as well.
We'll definitely fix this. Thanks for taking the time to report your issue! <3

**Comment by quinnblay** [comment]
Ah great, that works perfectly! Thanks for responding so quickly - love the experimental layout too
