### ISSUE TITLE
Android's virtual keyboard being closed at each keystroke with Dolphin browser

### ISSUE THREAD

**Issue by redox** [algolia/hn-search#26]
Need to investigate that

**Comment by raisedadead** [comment]
Is this still on going? 
I haven't been able to reproduce the issue with Android 5.1.1, Dolphin Browser 11.5.1 ( latest at time of this comment)

If you could share any specifics to share, I could look into it. 

Just got interested because have seen same trouble with Dolphin's native search earlier, got fixed a after a couple of updates to the app.

**Comment by redox** [comment]
Didn't have any news from here. Closing it until someone reproduces it.
