### ISSUE TITLE
2 clicks needed to open a link from the results page

### ISSUE THREAD

**Issue by seafoox** [algolia/hn-search#47]
It takes 2 clicks to open a link from the results page.
This issue only happens the first time. Once a result link has been opened, the issue

**Comment by redox** [comment]
This bug has been fixed with the new Angular-based rewriting. For the record, the issue was that the "change" event was triggered while leaving the search bar, before clicking on the link. Then before the actual click is triggered, the page was already re-rendered because "onchange" trigger the search.
