### ISSUE TITLE
Fuzzy match too fuzy

### ISSUE THREAD

**Issue by wumpus** [algolia/hn-search#54]
It used to be that I could search for things like [spacex] and [castar], now I am getting tons of non-SpaceX and non-CastAR results because it's considering "space" to be a match, etc etc.

When I use quotes I get what I wanted, but it's dropping the quotes in some circumstances, like:

* add quotes to query
* note that the URL now has quotes
* reload the page
* quotes are gone

**Comment by speedblue** [comment]
Hi,

Thanks for the feedback. In which circonstances are you annoyed by typo tolerance? In the sort by  popularity we are first sorting by the number of typos, so any result that match without typo will be before results with typos.

In the sort by date this is indeed an issue because we are not sorting by number of typos first. Maybe we should first sort on typo and only after on date. So you would have all results without typos sorted by date, then all results with 1 typos sorted by date, ....

Would it be better ?

**Comment by wumpus** [comment]
I am sorting by date. Really, I am OK with no typo support at all; what's necessary for Google isn't necessarily needed for HN search.

For the quote thing:

https://hn.algolia.com/?query=%22tesla%22&type=all&dateRange=all&prefix&page=0&sort=byDate#!%2Fcomment%2Fsort_by_date%2Fprefix%2F0%2Ftesla

You are rewriting the url to query=tesla

I suppose I should have opened 2 issues...

**Comment by speedblue** [comment]
For the typo tolerance, we will add a setting to let you disable it, it will be released soon.

For the quote bug, the URL is updated when the input box loses focus (on blur event). So if you have a query without quote, then add quotes and hit refresh without any other clic, you will maybe have the previous query. Can you try to clic outside of the search box before hitting refresh to check if this is the source of the problem?

**Comment by wumpus** [comment]
The above url shows a problem when I click on it, no mouse motion needed.

BTW you aren't supposed to rewrite the url like that; rewrite the fragment if you're going to rewrite.

**Comment by wumpus** [comment]
The fuzzy-match setting works great, thanks!

**Comment by speedblue** [comment]
You're welcome. For the quote issue we have try to reproduce it on different browsers without success. Can you give me the browser/version you are using?

Thanks

**Comment by wumpus** [comment]
With FF 35.0 on Mac, the above URL drops its quotes.

**Comment by wumpus** [comment]
FWIW I haven't had a problem with fuzzy match in a long time. Closing.
