### ISSUE TITLE
Add parameter to filter result set by character length

### ISSUE THREAD

**Issue by michaeldhopkins** [algolia/hn-search#6]
Hi, I am interested in getting sets of the longer Hacker News posts using the API.

Is it possible to have added to the search API a filter something like LengthFilters=CharLength>8000,WordLength>1000 similar to NumericFilters here? https://www.algolia.com/doc/rest_api#Indexes

If that's not the appropriate syntax/format/location for such a filter, I apologize. Hopefully my intention is clear.

**Comment by JonasBa** [comment]
@michaeldhopkins this would be possible if we added the attributes at indexing time and the search by applying numeric filters. Since we haven't had more interest in the last 5 years 😅I will close the issue. Feel free to let us know if this is very important to you or others potentionally interested and we'll reconsider it!
