### ISSUE TITLE
Strings like php, html, asp, uk... return false positives due to URL

### ISSUE THREAD

**Issue by canarduck** [algolia/hn-search#62]
![algolia-php](https://cloud.githubusercontent.com/assets/745865/8850650/0347fab2-314a-11e5-9140-8506fcb0fea0.png)

The first 3 results are good matches for `php` but the others are here just because their URL contains `.php` . The same happens with :
- html
- asp(x)
- jsp
- uk
- ...

**Comment by vvo** [comment]
@redox Maybe we could add another attribute like "domain name" and only search on it?

**Comment by redox** [comment]
> The first 3 results are good matches for php but the others are here just because their URL contains .php .

Sure, but is it really an issue? The results having a match in the title will always be before the one in the URL -> here you only have 3 because you filter on the "Past 24 hours".

If you're using our API, maybe what you want to do is avoid matching in the URL? By default we're search in `title, story_text, comment_text, url, author` -> but you can use the `restrictSearchableAttributes` to restrict that:

```
http://hn.algolia.com/api/v1/search?query=php&restrictSearchableAttributes=title,story_text,comment_text,author
```

What do you think?

**Comment by redox** [comment]
> @redox Maybe we could add another attribute like "domain name" and only search on it?

Yes that's definitely an option!

**Comment by canarduck** [comment]
@redox thanks, yes, if I set a wider time range the false positives disappear, at least from the first page. But still, I feel that some of those terms could be considered as stop words in your URL search.

I understand it could be a problem with your API, but maybe just on the frontend ?

**Comment by redox** [comment]
> But still, I feel that some of those terms could be considered as stop words in your URL search.

Yeah, we're handling stopwords a bit differently in Algolia: we don't have any "stopword" notion actually, we have "optional words" -> the records having those words will come before others record but it's not a big deal if an optional word if missing.

> I understand it could be a problem with your API, but maybe just on the frontend ?

Yeah so your issue is more about the UX right? Having results matching "php" in the URL after the interesting one matching in the title confuses you. I assume it will be the same for typos, right? -> after the hits that are matching exactly, you'll have approximative matches.

**Comment by canarduck** [comment]
> Having results matching "php" in the URL after the interesting one matching in the title confuses you

I would say it feels like the search engine is returning some really wrong results (which is, you are right, confusing :smiley: )

> so your issue is more about the UX right?
> after the hits that are matching exactly, you'll have approximative matches.

Yes it might only be an UX issue, maybe the approximative matches could be a little bit separated from the others, but then it would clutter your otherwise pretty clean interface.

**Comment by redox** [comment]
> maybe the approximative matches could be a little bit separated from the others, but then it would clutter your otherwise pretty clean interface.

Yes I was also thinking about something like that :+1: @Shipow your thoughts?

**Comment by wumpus** [comment]
The thing I'd be most concerned about is that example.com/foo.php ranks below example.com/information-about-php/

Other than that, it's just a UX issue. But it's a familiar one: people are used to the concept that Google results sometimes have webpages that don't contain the search terms -- because the search terms are in incoming anchortext. They don't understand the why, but they know that it happens.

**Comment by seanjensengrey** [comment]
I would actually *like* to search in the url. So it would be nice to add faceted search for urls via

`url:youtube and not url:php` or `-url:php` or `+url:youtube.com`
