### ISSUE TITLE
hn-ask no url

### ISSUE THREAD

**Issue by RockyRx** [algolia/hn-search#96]
Is there a way to get the Ask HN url? It currently returns ```null``` 

Thanks.

**Comment by redox** [comment]
Hey @RockyRx,

aren't the "Ask HN" always linking to `https://news.ycombinator.com/item?id=<STORY_ID>`?

**Comment by RockyRx** [comment]
@redox If I call ```http://hn.algolia.com/api/v1/search_by_date?tags=story``` and then fetch the URL it always returns a ```null```

**Note:** this only happens for 'Ask HN' only. Others (stories) has the ```url```. You can check this via 

> https://hn.algolia.com/?%20%7B%20%7B%20%20settings.style%20=%3D%3D%20%22experimental%22%20%3F%20%22experimental%22%20:%20%22%22%20%7D%7D&query=&sort=byPopularity&prefix&page=0&dateRange=last24h&type=story

Check the resulting json

**Comment by redox** [comment]
Sure, but that's because `Ask HN` are not submitted with an URL but with a text on HN. So this is expected. What you can do is to use `https://news.ycombinator.com/item?id=<STORY_ID>` when the `url` field is `null`; which means it's only a discussion on HN and not a link to an external website.

Is that correct? How does it sound to you?

**Comment by RockyRx** [comment]
@redox, yeah that's sound okay. Thanks for the tip.
